### ISSUE TITLE
Create new repo for Ambari plugin

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-yarn#69]
As a developer, I'd like to create a separate repo for SCDF-Yarn's Ambari plugin, so they're separated and maintained independently from the core project.

**Comment by jvalkeal** [comment]
I propose repo names `spring-cloud-dataflow-rpm` and `spring-cloud-dataflow-ambari-rpm`. If we some day want to build debian packages, we need separate repo/build because artifactory plugin from jfrog cannot upload to multiple repos during a build. yum and apt repos would really be separate repos in artifactory.

**Comment by sabbyanandan** [comment]
@markpollack: ^^ - thoughts, please?

**Comment by trisberg** [comment]
Do we need spring-cloud-dataflow-rpm? I would assume that it would only be
used for Ambari installs.

-Thomas

**Comment by jvalkeal** [comment]
we still need to build that rpm!

**Comment by jvalkeal** [comment]
if comment was related why we don't build both rpm's in a same project, blame artifactory plugin for that. we need separate repos.

**Comment by trisberg** [comment]
ok, get it now
